server:
  port: 9090
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-type: PKCS12
    key-store-password: 12345678
    key-password: 12345678
    key-alias: mykey
    trust-store: classpath:truststore.jks
    trust-store-password: 12345678
#    client-auth: need

spring:
 application:
   name: Fapi2.0_client
   output.ansi.enabled: ALWAYS
 security:
   oauth2:
     client:
       provider:
         spring:
           issuer-uri: https://www.certification.openid.net/test/a/cbuae-rp/
       registration:
         reg-client:
           provider: spring
           client-id: 122444
           client-secret: "secret"
           authorization-grant-type: authorization_code
           client-authentication-method: client_secret_basic
           redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
           scope: accounts,openid

logging:
  level:
    org.springframework.web: DEBUG
    com.pay10ae.Fapi2: INFO